### ISSUE TITLE
Add support for OSX Command key as alt

### ISSUE THREAD

**Issue by andyreagan** [avendael/atomic-emacs#140]
I'm not sure if the best way to replicate this emacs behavior is to somehow remap the key within text editing, or to just edit the `alt` commands to also have `cmd` in them.
I've done the latter, which amounts to adding the following to by user config:
```
'body':
  'cmd-x': 'command-palette:toggle'

'body.platform-darwin':
  'cmd-x': 'atomic-emacs:cut'
  'cmd-c': 'atomic-emacs:copy'

'atom-workspace atom-text-editor':
  # Navigation
  'cmd-b': 'atomic-emacs:backward-word'
  'cmd-left': 'atomic-emacs:backward-word'
  'cmd-f': 'atomic-emacs:forward-word'
  'cmd-right': 'atomic-emacs:forward-word'
  'cmd-{': 'atomic-emacs:backward-paragraph'
  'cmd-}': 'atomic-emacs:forward-paragraph'
  'cmd-m': 'atomic-emacs:back-to-indentation'
  'cmd-<': 'core:move-to-top'
  'cmd->': 'core:move-to-bottom'

  # Killing & Yanking
  'cmd-backspace': 'atomic-emacs:backward-kill-word'
  'cmd-delete': 'atomic-emacs:backward-kill-word'
  'cmd-d': 'atomic-emacs:kill-word'
  'cmd-w': 'atomic-emacs:copy-region-as-kill'
  'cmd-y': 'atomic-emacs:yank-pop'
  'cmd-shift-y': 'atomic-emacs:yank-shift'

  # Editing
  'cmd-\\': 'atomic-emacs:delete-horizontal-space'
  'cmd-^': 'atomic-emacs:delete-indentation'
  'cmd-space': 'atomic-emacs:just-one-space'
  'cmd-t': 'atomic-emacs:transpose-words'
  'cmd-l': 'atomic-emacs:downcase-word-or-region'
  'cmd-u': 'atomic-emacs:upcase-word-or-region'
  'cmd-c': 'atomic-emacs:capitalize-word-or-region'
  'cmd-/': 'autocomplete-plus:activate'
  'cmd-q': 'autoflow:reflow-selection'
  'cmd-;': 'editor:toggle-line-comments'

  # Marking & Selecting

  # UI
  'cmd-.': 'symbols-view:toggle-file-symbols'

'atom-text-editor:not(.autocomplete-active):not(.mini)':
  # Scrolling
  'cmd-v': 'atomic-emacs:scroll-down'

'.platform-linux atom-workspace, .platform-win32 atom-workspace':
  'cmd-g g': 'go-to-line:toggle'
  'cmd-g cmd-g': 'go-to-line:toggle'

'.platform-darwin':
  'cmd-g g': 'go-to-line:toggle'
  'cmd-g cmd-g': 'go-to-line:toggle'
```

**Comment by andyreagan** [comment]
Edit: I actually commented out to `cmd-c` and `cmd-v` because I like to preserve some of the default OSX bindings here.

**Comment by oggy** [comment]
How are these bindings working for you? My hunch would have been that there would be a lot that conflict with other MacOS defaults, but if you find this a better experience, then I'm open to adding this as an option.

I can't think of a great way of doing it. What I'd probably do is have a setting toggle a class on the atom workspace and bind the alternative commands under that. We'd still need to maintain this extra copy of the bindings, though.

What I do instead of this is just swap command & alt system-wide. One benefit is that other apps that support Emacs-ish bindings behave more consistently, e.g. terminals, browsers, etc. It'd take a little time to adapt to, though.

**Comment by aguynamedben** [comment]
Also see https://github.com/avendael/atomic-emacs/issues/131

I use Command as Meta, which sucks because what I think is Meta-W (copy) is hijacked by macOS and closes the Atom tab... then I just go back to using Emacs. =)

If I could figure out how to tell atomic-emacs that to forget about macOS shortcuts (this is what I do in Emacs) then I'd probably give Atom more of a shot.

**Comment by andyreagan** [comment]
I've been using this for a while now, and it's been working smoothly.
It's just a different setup that the one that you proposed, but I like where the command key on OSX is over where the alt key is.
Meta-W still works for copy with this setting (doesn't close Atom for me).

I don't think these changes should be merged, just because it's my setup. But now people can find this thread if they want them. Somehow adding a checkbox to enable these in settings would be cool, but I'm not sure how useful ultimately. People can just customize it.

**Comment by aguynamedben** [comment]
Maybe it's more of a feature request than a help request, but I still think it would be nice if atomic-emacs had a feature that supported moving around Alt/Meta. In Emacs moving around Meta/Super/Control/Hyper is very easy:

```
;; set keys for Apple keyboard, for emacs in OS X
;; http://ergoemacs.org/emacs/emacs_hyper_super_keys.html
(setq mac-command-modifier 'meta) ; make cmd key do Meta
(setq mac-option-modifier 'super) ; make opt key do Super
(setq mac-control-modifier 'control) ; make Control key do Control
(setq ns-function-modifier 'hyper)  ; make Fn key do Hyper
```

**Comment by aguynamedben** [comment]
FWIW I documented what I did to change Meta to Command here: https://github.com/avendael/atomic-emacs/issues/131#issuecomment-369678759
