### ISSUE TITLE
ctrl-k takes up to 2 seconds

### ISSUE THREAD

**Issue by dlandis** [avendael/atomic-emacs#75]
Atom version 1.0.0 on windows 7

ctrl-k seems to work properly in terms of function, but after doing the keystroke it takes up to 2 seconds before the line is cut.

performance seems fine for other keybindings, not sure why just this one would take so long. basically makes this keybinding unusable.

**Comment by oggy** [comment]
This happens because [Atom's built-in windows keymap](https://github.com/atom/atom/blob/master/keymaps/win32.cson#L68-L79) has `ctrl-k` bound as a prefix of other commands. The way Atom resolves this is to wait a couple of seconds for another keystroke, and dispatch accordingly. Pressing `ctrl-k` again will force it to dispatch the original `ctrl-k` (without running it twice).

This isn't ideal, but I'm not sure there's anything atomic-emacs can do about it. Seems like most appropriate is to disable the built-in Atom bindings for `ctrl-k` if you don't use them, but I don't know of a sanctioned way of doing that, and it certainly seems outside the scope of atomic-emacs. Feel free to reopen if you have a better suggestion.

Thanks for reporting!

**Comment by oggy** [comment]
Actually I'm wrong: pressing `ctrl-k` twice does run it twice. Binding to `ctrl-k ctrl-k` seems like a reasonable compromise, though.

**Comment by dlandis** [comment]
@oggy You can use `unset!` to disable the bindings for `ctrl-k` apparently [but there is a bug](https://github.com/atom/atom-keymap/issues/78) preventing that from working properly.

**Comment by oggy** [comment]
Thanks, I've subscribed to that issue. Would be nice if the unset mechanism could be opt-in too, as some may find such a move invasive. For now I'll push a binding for `ctrl-k ctrl-k` which at least lets you push the key again to force it now.

**Comment by holtzermann17** [comment]
**Putting this in keymap.cson fixes it**

``` cson
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-k ctrl-0': 'unset!'
  'ctrl-k ctrl-1': 'unset!'
  'ctrl-k ctrl-2': 'unset!'
  'ctrl-k ctrl-3': 'unset!'
  'ctrl-k ctrl-4': 'unset!'
  'ctrl-k ctrl-5': 'unset!'
  'ctrl-k ctrl-6': 'unset!'
  'ctrl-k ctrl-7': 'unset!'
  'ctrl-k ctrl-8': 'unset!'
  'ctrl-k ctrl-9': 'unset!'

'body':
  'ctrl-k ctrl-alt-w': 'unset!'
  'ctrl-k ctrl-down': 'unset!'
  'ctrl-k ctrl-left': 'unset!'
  'ctrl-k ctrl-n': 'unset!'
  'ctrl-k ctrl-p': 'unset!'
  'ctrl-k ctrl-right': 'unset!'
  'ctrl-k ctrl-up': 'unset!'
  'ctrl-k ctrl-w': 'unset!'
  'ctrl-k down': 'unset!'
  'ctrl-k left': 'unset!'
  'ctrl-k right': 'unset!'
  'ctrl-k up': 'unset!'
  'ctrl-k up': 'unset!'

'.platform-win32, .platform-linux':
  'ctrl-k ctrl-b': 'unset!'

'.platform-win32 atom-text-editor, .platform-linux atom-text-editor':
  'ctrl-k ctrl-d': 'unset!'

'atom-workspace atom-text-editor':
  'ctrl-k ctrl-l': 'unset!'
  'ctrl-k ctrl-u': 'unset!'


'.platform-win32 .tree-view, .platform-linux .tree-view':
  'ctrl-k down': 'unset!'
  'ctrl-k h': 'unset!'
  'ctrl-k j': 'unset!'
  'ctrl-k k': 'unset!'
  'ctrl-k l': 'unset!'
  'ctrl-k left': 'unset!'
  'ctrl-k right': 'unset!'
```
