### ISSUE TITLE
Kill the line + yank ignores the newline character

### ISSUE THREAD

**Issue by wende** [avendael/atomic-emacs#93]
In emacs when killing the whole line and then yanking it, it gets pasted with the newline character.
In this package instead of 
```
  #line 1
  #line 2
```
you get
```
#line 1  #line 2
```

**Comment by oggy** [comment]
@wende Thanks for the report. This is because atomic-emacs doesn't currently implement proper kill-ring functionality. It's coming soon, though: there is a branch called kill-ring you can try if you can put up with a couple of minor bugs. I'm working on ironing these out, but feel free to report any issues you come across there.

**Comment by oggy** [comment]
Fixed in 0.9.0.
