### ISSUE TITLE
Seamless integration with system clipboard broken

### ISSUE THREAD

**Issue by artagnon** [avendael/atomic-emacs#95]
With the latest update, <kbd>alt</kbd>-<kbd>w</kbd> doesn't allow pasting into other applications, and <kbd>ctrl</kbd>-<kbd>y</kbd> doesn't yank from other applications. Having a universal <kbd>cmd</kbd>-<kbd>c</kbd>, <kbd>cmd</kbd>-<kbd>v</kbd> is aesthetically pleasing; in the previous version, the emacs keybindings did read/write to system clipboard.

**Comment by oggy** [comment]
Thanks for the feedback @artagnon!

I've just merged @itiut's patch. Going the other way (yanking from other apps) is an interesting idea, but tricky to implement, since we can't tell if the copy happened before or after the last kill ring entry without having a clipboard timestamp. The only alternative I can think of is to poll the clipboard, which is rather unsatisfying for several reasons.

I'll mark this as resolved, and keep thinking on the yank issue. Let me know if you have further thoughts.

**Comment by artagnon** [comment]
On the issue of keeping track of kills (ring), I like clipboard-plus.
